
#ifndef MAININCLUDEFILES_H_
#define MAININCLUDEFILES_H_

#include "trigonalpl_structure_na.h"
#include "trigonalpl_structure_ca.h"
#include "trigonalpl_structure_k.h"
#include "trigonalpl_structure_mg.h"
#include "trigonalpl_structure_mn.h"
#include "trigonalpl_structure_fe.h"
#include "trigonalpl_structure_cu.h"
#include "trigonalpl_structure_zn.h"
#include "trigonalpl_structure_co.h"
#include "trigonalpl_structure_pb.h"
#include "trigonalpl_structure_hg.h"
#include "trigonalpl_structure_as.h"
#include "trigonalpl_structure_cd.h"
#include "trigonalpl_structure_ni.h"
#include "trigonalplanar.h"

#include "tetragonalpl_structure_mg.h"
#include "tetragonalpl_structure_fe.h"
#include "tetragonalpl_structure_cd.h"
#include "tetragonalpl_structure_ni.h"
#include "tetragonalplanar.h"

#include "trigonalbipyr_structure_na.h"
#include "trigonalbipyr_structure_ca.h"
#include "trigonalbipyr_structure_mg.h"
#include "trigonalbipyr_structure_mn.h"
#include "trigonalbipyr_structure_fe.h"
#include "trigonalbipyr_structure_zn.h"
#include "trigonalbipyr_structure_co.h"
#include "trigonalbipyr_structure_hg.h"
#include "trigonalbipyr_structure_cd.h"
#include "trigonalbipyr_structure_ni.h"
#include "trigonal_bipyramidal.h"

#include "tetragonalpyr_structure_na.h"
#include "tetragonalpyr_structure_ca.h"
#include "tetragonalpyr_structure_mg.h"
#include "tetragonalpyr_structure_cd.h"
#include "tetragonalpyr_structure_ni.h"
#include "tetragonalpyr_structure_zn.h"
#include "tetragonal_pyramidal.h"

#include "tetra_structure_na.h"
#include "tetra_structure_ca.h"
#include "tetra_structure_k.h"
#include "tetra_structure_mg.h"
#include "tetra_structure_mn.h"
#include "tetra_structure_fe.h"
#include "tetra_structure_cu.h"
#include "tetra_structure_zn.h"
#include "tetra_structure_co.h"
#include "tetra_structure_pb.h"
#include "tetra_structure_hg.h"
#include "tetra_structure_as.h"
#include "tetra_structure_cd.h"
#include "tetra_structure_ni.h"
#include "tetra_structure_cs.h"

#include "octa_structure_na.h"
#include "octa_structure_ca.h"
#include "octa_structure_mg.h"
#include "octa_structure_mn.h"
#include "octa_structure_fe.h"
#include "octa_structure_cd.h"
#include "octa_structure_ni.h"
#include "octa_structure_zn.h"
#include "octa_structure_co.h"
#include "octahedral.h"

#endif /* MAININCLUDEFILES_H_ */
